version: '3.3'
services:
   postgres-vapor:
      image: postgres
      ports:
         - "5432:5432"
      environment:
         POSTGRES_DB: vapor
         POSTGRES_USER: vapor
         POSTGRES_PASSWORD: password
